### ISSUE TITLE
Request: assets

### ISSUE THREAD

**Issue by konsumer** [JayPavlina/super-mario-bros-crossover#1]
I would love to try to port your amazing game to other systems. Would you consider putting the images/etc in some other format? Are these originally image files, or like some embedded-in-source pixel format? (I notice you have pallet images and stuff.)

**Comment by JayPavlina** [comment]
I am kind of hesitant to post them due to copyright issues. You should be able to extract them from the swf of the game.

**Comment by konsumer** [comment]
No prob, totally understandable!
